version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 8001:8001
    image: app:django
    container_name: django_container
    command: >
      bash -c "echo runningDocker
      && python manage.py runserver 0.0.0.0:8001"
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_db